engines:
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
  - "**.coffee"
  - "**.js"
exclude_paths:
- gulpfile.coffee
- README.md
- circle.yml
- package.json
- doc/javascript/application.js